Source/Internal/API/APIEndpoints.swift, Source/Models/VirtusizeEnvironment.swift, Tests/APIEndpointsTests.swift, Tests/APIEventTests.swift
Update the event API URL to "https://events.staging.virtusize.jp" for staging and "https://events.virtusize.{env}" for production
=> Feature: Change the event API URL

Colors.swift, Example/Example.xcodeproj/project.pbxproj, Source/Internal/API/APIRequest.swift, Source/Internal/Constants/Assets.swift, Source/Internal/Models/SizeComparisonRecommendedSize.swift, Source/Internal/Models/VirtusizeGetSizeParams.swift, Source/Internal/Models/VirtusizeInternalProduct.swift, Source/Internal/Models/VirtusizeStoreProduct.swift, Source/Internal/Views/VirtusizeProductImageView.swift, Source/Internal/Workers/FindBestFitHelper.swift, Source/Internal/Workers/UserDefaultsHelper.swift, Source/Models/VirtusizeParams.swift, Source/UI/VirtusizeInPageMini.swift, Source/UI/VirtusizeInPageStandard.swift, Source/UI/VirtusizeInPageView.swift, Source/UI/VirtusizeView.swift, Source/UI/VirtusizeWebViewController.swift, Source/Virtusize.swift, Tests/FindBestFitHelperTests.swift, Tests/StoreProductFixtures.swift, Tests/VirtusizeGetSizeParamsTests.swift, Tests/VirtusizeStoreProductTests.swift, Tests/VirtusizeTests.swift, Virtusize.xcodeproj/project.pbxproj
**When the width of InPage is smaller than 343pt**
**Note:** Due to the session issue, I need to log in to Aoyama every time I open it for now.
Device: iPhone 5s simulator, whose InPage width is smaller than 343pt
**Note:** Due to the session issue, I need to log in to Aoyama every time I open it for now.
***A user logs in***
***A user logs out***
***A user selects a different product***
=> Feature: Item x Item Comparison UI 

CHANGES.md, Example/Example/ViewController.swift, README-JP.md, README.md, ROADMAP.md, Source/UI/VirtusizeWebViewController.swift, Virtusize.podspec
virtusizeControllerShouldClose is removed from VirtusizeMessageHandler since it won't be needed.
=> Hotfix/2.1.2: Ensure dismissing the Virtusize web view by the SDK

Example/Example/ViewController.swift, README-JP.md, README.md, Source/UI/VirtusizeInPageMini.swift, Source/UI/VirtusizeInPageStandard.swift
so that clients can change the font sizes of InPage
=> Feature: Enable font size changes

Source/Internal/API/APIEndpoints.swift, Source/Internal/API/APIRequest.swift, Source/Internal/API/VirtusizeAPIService.swift, Source/UI/VirtusizeInPageView.swift, Source/VirtusizeRepository.swift
When a user logs out of Aoyama, the SDK will make an API call to `/user-products` to re-fetch user items. the product list is expected to be empty from the server, but in fact, the product list includes the items that the user has created before they log in and then log out, which causes InPage does not display "Find the right size ..." when a user logs out.
=> Fix: the wrong InPage message when a user logs out

Source/Internal/Constants/Colors.swift, Source/UI/VirtusizeInPageStandard.swift
=> Fix: the shadow of InPage

Example/Example.xcodeproj/project.pbxproj, Example/Example/ViewController.swift, Example/Example/WebViewController.swift, Source/VirtusizeWebView.swift, Virtusize.xcodeproj/project.pbxproj
The main idea is that clients can replace their WKWebview with VirtusizeWebview and still can use all the functionalities that WKWebview provides.
There's an issue about x-vs-auth being not persistent in the local storage on our domain such as staging.virtusize.com once a user force-closes the iOS app. It might not be an urgent deal because right now this is how it currently works with the Virtusize log in flow on client's web view apps. 
Wes and I are planing to solve it by exchanging x-vs-auth between SDK and Virtusize integration (previously called Aoyama) and save this token in the app's storage to avoid any issues that might be potentially caused by cookies and local storage.
If the app is killed, the user won't be logged in anymore
=> The SNS issue fix with the SDK

Example/Example/WebViewController.swift, Source/UI/VirtusizeWebViewController.swift, Source/VirtusizeWebView.swift
The SNS buttons are hidden by default when Aoyama is loaded in a web view.
To enable these buttons, the webview executes `window.virtusizeSNSEnabled = true;` when the webpage has finished loading.
**Before**
**After**
=> Feature: Enable SNS buttons for the webview

.github/pull_request_template.md, .github/workflows/pull-request-checks.yml, .github/workflows/release.yml, Makefile, README-JP.md, README.md, Virtusize.xcodeproj/project.pbxproj, Virtusize.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Virtusize.xcodeproj/xcshareddata/xcschemes/Virtusize.xcscheme, Virtusize.xcodeproj/xcshareddata/xcschemes/VirtusizeTests.xcscheme, Virtusize/Sources/VirtusizeWebView.swift, Virtusize/Tests/APIEventTests.swift
1. Create `.github/workflows/pull-request-checks.yml` to run lint checks and tests triggered by pull requests.
2. Create `.github/workflows/release.yml` to deploy the SDK to CocoaPods triggered by Github releases
3. Create `.github/pull_request_template.md` for the pull request template 
4. Update README for the requirement of the Xcode version from 11.0+ to 12.0+. 
Tried to run `make build` on the Github actions virtual environment with Xcode 11.2.1 (/Applications/Xcode_11.2.1.app/Contents/Developer) and it had an error shown as follows because this function of the WKWebview is only available for iOS 14.0+ and only Xcode 12+ supports iOS 14+
[Ref for Xcode vs. iOS versions](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#installed-sdks) …
=> Feature: Setup GitHub Actions and create a PR template

CHANGES.md, Example/Example.xcodeproj/project.pbxproj, Example/Example.xcodeproj/xcshareddata/xcschemes/Example.xcscheme, Package.swift, README-JP.md, README.md, Virtusize.podspec, Virtusize.xcodeproj/project.pbxproj, Virtusize.xcodeproj/xcshareddata/xcschemes/Virtusize.xcscheme, Virtusize.xcodeproj/xcshareddata/xcschemes/VirtusizeTests.xcscheme, Virtusize/Sources/VirtusizeConfiguration.swift, Virtusize/Tests/APIEventTests.swift, VirtusizeCore.podspec, VirtusizeCore/VirtusizeCore.xcodeproj/project.pbxproj, VirtusizeCore/VirtusizeCore.xcodeproj/xcshareddata/xcschemes/VirtusizeCore.xcscheme, VirtusizeCore/VirtusizeCore.xcodeproj/xcshareddata/xcschemes/VirtusizeCoreTests.xcscheme
Worked on following changes in NSDK-164:
Cleanup - Update deployment target iOS 10.3 to iOS 12.0
Cleanup - Update APIEventTests.swift for package version 
Cleanup - Update Tag version in Virtusize.podspec
Doc - Update readme file for Requirements: iOS 12.0 Doc - Update CHANGES for 2.5.2
=> Cleanup: Update deployment target iOS 10.3 to iOS 12.0

CHANGES.md, Example/Sources/AppDelegate.swift, README-JP.md, README.md, Virtusize.podspec, Virtusize.xcodeproj/project.pbxproj, Virtusize/Sources/Flutter/VirtusizeFlutterReposiory.swift, Virtusize/Sources/Internal/API/APIEndpoints.swift, Virtusize/Sources/Internal/API/VirtusizeAPIRequest.swift, Virtusize/Sources/Internal/API/VirtusizeAPIService.swift, Virtusize/Sources/Internal/Models/VirtusizeAnyCodable.swift, Virtusize/Sources/Internal/Models/VirtusizeGetSizeItemsParam.swift, Virtusize/Sources/Internal/Models/VirtusizeGetSizeParams.swift, Virtusize/Sources/Models/BodyProfileRecommendedSize.swift, Virtusize/Sources/Models/VirtusizeEnvironment.swift, Virtusize/Sources/Virtusize.swift, Virtusize/Sources/VirtusizeConfiguration.swift, Virtusize/Sources/VirtusizeRepository.swift, Virtusize/Tests/APIEndpointsTests.swift, Virtusize/Tests/APIEventTests.swift, Virtusize/Tests/APIRequestTests.swift, Virtusize/Tests/VirtusizeGetSizeParamsTests.swift, VirtusizeCore/Sources/API/APIService.swift
…nctions/size-rec/get-size ➝ https://size-recommendation.virtusize.jp/item
- Refactor: Change the get-size endpoint from https://services.virtusize.jp/ds-functions/size-rec/get-size ➝ https://size-recommendation.virtusize.jp/item
- Refactor: Change in request body of VirtusizeGetSizeParams: Remove "modelInfo" key,  in "gender" now getting value from VirtusizeUserBodyProfile
- Refactor: Change in Responce Model of BodyProfileRecommendedSize
- Docs: Update Readme file to update pod version
|
https://app.clickup.com/t/3702259/NSDK-177
=> Update size recommendation endpoints in iOS SDK

.github/workflows/pull-request-checks.yml, Example/Example.xcodeproj/project.pbxproj, Makefile, Virtusize/Sources/Resources/PrivacyInfo.xcprivacy
1. Removed unnecessary privacy manifest API type NSPrivacyAccessedAPICategoryFileTimestamp
References:
https://developer.apple.com/videos/play/wwdc2023/10060/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393
2. Updated the example app's bundle ID to com.virtusize.Example and the development team to None.
3. Updated the build destination (iPhone 8 is too old)
4. Fixed the Github action issue regarding SwiftLint
None
https://app.clickup.com/t/3702259/NSDK-181
=> [NSDK-181] Update current privacy manifest

CHANGES.md, Virtusize/Sources/Flutter/VirtusizeFlutterReposiory.swift, Virtusize/Sources/Internal/API/APIEndpoints.swift, Virtusize/Sources/Internal/API/VirtusizeAPIRequest.swift, Virtusize/Sources/Internal/API/VirtusizeAPIService.swift, Virtusize/Sources/Models/BodyProfileRecommendedSize.swift, Virtusize/Sources/UI/VirtusizeWebViewController.swift, Virtusize/Sources/VirtusizeConfiguration.swift, Virtusize/Sources/VirtusizeRepository.swift, Virtusize/Tests/APIEndpointsTests.swift, Virtusize/Tests/APIRequestTests.swift, Virtusize/Tests/VirtusizeAPIServiceTests.swift, VirtusizeCore/Sources/API/APIService.swift
- Fetched the latest Aoyama version from https://static.api.virtusize.com/a/aoyama/latest.txt
- Updated the Virtusize web view URL to the following format: https://static.api.virtusize.jp/a/aoyama/$version/sdk-webview.html
=> [NSDK-213] Update Virtusize WebView URL

CHANGES.md, Package.swift, Virtusize.podspec, Virtusize/Sources/Flutter/VirtusizeFlutterReposiory.swift, Virtusize/Sources/Virtusize.swift, Virtusize/Sources/VirtusizeRepository.swift, Virtusize/Tests/APIEndpointsTests.swift, VirtusizeCore/Sources/Workers/UserDefaultsHelper.swift
If we click on the native UI component like VirtusizeButton, VirtusizeInPageStandard, and VirtusizePageMini when the user-session request is not finished yet, the web view page will be in the loading state forever because the data sent via vsParamsFromSDK lacks session data.
We need to make sure we get the user session data from the server before opening the web view.
When notifying productDataCheck (finished) to the UI components, the UI component becomes unhidden, so making sure to get the user session data before broadcasting the notification will solve the issue, which is the fastest way due to the limited development time.
=> [NSDK-220] Fix the WebView Indefinite Loading Issue

CHANGES.md, Virtusize.podspec, Virtusize/Sources/Internal/Utils/Image+Extensions.swift, Virtusize/Sources/Internal/Utils/Localization.swift, Virtusize/Sources/VirtusizeConfiguration.swift, VirtusizeCore/Sources/Utils/BundleLoaderProtocal.swift, VirtusizeCore/Sources/Utils/VirtusizeCoreBundleLoader.swift
=> [NSDK-228] Hotfix 2.6.1 – Fix for Duplicate VirtusizeCore Bundles

.github/workflows/pull-request-checks.yml, CHANGES.md, Example/Sources/AppDelegate.swift, README.md, VirtusizeCore/Sources/Utils/VirtusizeLogger.swift, VirtusizeCore/Tests/Utils/VirtusizeLoggerTests.swift, VirtusizeCore/VirtusizeCore.xcodeproj/project.pbxproj
Explain the current situation of the code
- It's hard to debug Main and Auth libraries, as all the "debug" code should deleted before the release. It's important to occasionally turn on/off debugging code for inspection
=> Internal Logger

.githooks/pre-push, .github/workflows/pull-request-checks.yml, Makefile, Scripts/build_fonts.sh, Scripts/validate_fonts.sh
We've discussed a way to re-build the fonts automatically.  
There are two downsides:
1. There should be a new commit to ensure created fonts are available from repository
2. If there are no changes to the localisation - the fonts are recreated anyway which make unnecessary grow of the repository size
Still, to achieve the goal and ensure the fonts are valid, a new script introduced to check if the existing font subset supports all the characters from the corresponding localization files.
- Currently if the localisation modified, there is no guarantee the new characters are supported by the previously created fonts
=> Validate fonts on push (PR and git-hooks)

Virtusize/Tests/VirtusizeAPIServiceTests.swift
- Particular unit-test occasionally fail the build: `testFetchLatestAoyamaVersion`
=> Fix unit-tests

CHANGES.md, VirtusizeAuth/Sources/API/FacebookAPIRequest.swift, VirtusizeAuth/Sources/API/GoogleAPIRequest.swift
- Important `VirtusizeAuth` via Swift Package Manager leads to compilation error, due to missing `import Foundation`
=> Fix SPM reference

.github/workflows/release.yml, CHANGES.md
- Pods release fails, because local CocoaPods repository stays outdated (due to CDN nature)
=> Fix pods release flow

CHANGES.md, Virtusize/Sources/UI/VirtusizeWebViewController.swift
- SNS still visible even thought `.setShowSNSButtons(false)` configured
=> Ensure SNS buttons are hidden when configured to do so

CHANGES.md, Virtusize/Sources/Internal/API/APIEndpoints.swift, Virtusize/Tests/APIEndpointsTests.swift, Virtusize/Tests/APIRequestTests.swift
- Product Types always loaded from the origin server, while it's data persistent and could be easily cached
=> Use cache-friendly endpoint to load product types

CHANGES.md, Virtusize/Sources/Models/BodyProfileRecommendedSize.swift, Virtusize/Tests/VirtusizeAPIServiceTests.swift, VirtusizeCore/Sources/API/APIService.swift
- Numeric size recommendations sometimes do not appear
=> Fix an issue when numeric size recommendations do not appear

CHANGES.md, Virtusize/Sources/VirtusizeConfiguration.swift
- Local strings are not loaded when using Cocoapods (after pods refactoring in 2.8.x)
=> Fix local strings loading when using Pods

CHANGES.md, VirtusizeCore/Sources/Resources/Localizations/en.lproj/VirtusizeLocalizable.strings, VirtusizeCore/Sources/Resources/Localizations/ja.lproj/VirtusizeLocalizable.strings, VirtusizeCore/Sources/Resources/Localizations/ko.lproj/VirtusizeLocalizable.strings
Virtusize SDK's inpage buttons text is not the same as in web version.
=> Align Virtusize button texts with Aoyama

CHANGES.md, README-JP.md, README.md, Virtusize/Sources/Models/VirtusizeParamsBuilder.swift
Sns buttons are hidden by default and should be enabled by setting showSNSButtons: true in VirtusizeParamsBuilder.
=> Make sns buttons show by default

CHANGES.md, Virtusize/Sources/Internal/Models/VirtusizeGetSizeParams.swift, Virtusize/Sources/Internal/Models/VirtusizeGetSizeParamsShoe.swift
Explain the current situation of the code
There is a compilation error when packages added via Swift Package Manager, due to missing explicit `import Foundation`
=> Fix import Foundation error

CHANGES.md, Virtusize/Sources/Flutter/VirtusizeFlutter.swift, Virtusize/Sources/Flutter/VirtusizeFlutterProductEventHandler.swift
Language change event on web is not handled in Flutter SDK buttons.
Flutter SDK handles the language change event on web.
=> Handle language change on web in Flutter SDK implementation
