virtusize/integration_ios

README.md

Add instruction to install SDK with [Carthage](https://github.com/Carthage/Carthage)

:pencil: Add support to Carthage

---

Source/Internal/API/APIEndpoints.swift
Source/Internal/API/APIEvent.swift
Source/Internal/API/APIRequest.swift
Source/Internal/Constants/Assets.swift
Source/Internal/Views/SplashView.swift
Source/Internal/Workers/BrowserID.swift
Source/Internal/Workers/Deserializer.swift
Source/Models/VirtusizeEnvironment.swift
Source/Models/VirtusizeError.swift
Source/Models/VirtusizeEvent.swift
Source/Models/VirtusizeProduct.swift
Source/UI/VirtusizeButton.swift
Source/UI/VirtusizeViewController.swift
Source/Virtusize.swift

Adds explanation comments for methods, properties and structures, etc.

Document methods

---

Example/Example/ViewController.swift
Source/Internal/API/APIEndpoints.swift
Source/Internal/API/APIRequest.swift
Source/Models/VirtusizeError.swift
Source/Models/VirtusizeOrder.swift
Source/Models/VirtusizeOrderItem.swift
Source/Models/VirtusizeOrderItemParams.swift
Source/Models/VirtusizeStore.swift
Source/Virtusize.swift
Virtusize.xcodeproj/project.pbxproj

Create the order method in the SDK

---

CHANGES.md
README.md

Bump to 1.3.1

---

Source/Internal/API/APIEndpoints.swift
Source/Internal/API/APIRequest.swift
Source/Models/VirtusizeBrandSizing.swift
Source/Models/VirtusizeProductSize.swift
Source/Models/VirtusizeStoreProduct.swift
Source/Models/VirtusizeStoreProductAdditionalInfo.swift
Source/Models/VirtusizeStoreProductMeta.swift
Source/Virtusize.swift
Tests/APIEndpointsTests.swift
Tests/APIEventTests.swift
Tests/APIRequestTests.swift
Tests/TestFixtures.swift
Tests/VirtusizeBrandSizingTests.swift
Tests/VirtusizeProductSizeTests.swift
Tests/VirtusizeStoreProductAdditionalInfoTests.swift
Tests/VirtusizeStoreProductMetaTests.swift
Tests/VirtusizeStoreProductTests.swift
Tests/VirtusizeTests.swift
Virtusize.xcodeproj/project.pbxproj

Feature: API integration to get the info of a product

---

CHANGES.md
Example/Example/ViewController.swift
README.md
Source/Internal/Utils/HTTPURLResponse+Extensions.swift .swift
Source/Models/VirtusizeError.swift
Source/Models/VirtusizeOrder.swift
Source/Models/VirtusizeOrderItem.swift
Source/Virtusize.swift
Tests/TestFixtures.swift
Virtusize.podspec
Virtusize.xcodeproj/project.pbxproj

Fix the Order API error saying the API key and the external product ID are not provided

Hotfix: Fix the Order API error for version 1.x.x

---

Source/Internal/Views/VirtusizeProductImageView.swift
Source/Localizations/en.lproj/VirtusizeLocalizable.strings
Source/Localizations/ja.lproj/VirtusizeLocalizable.strings
Source/Localizations/ko.lproj/VirtusizeLocalizable.strings
Source/UI/VirtusizeButton.swift
Source/UI/VirtusizeInPageMini.swift
Source/UI/VirtusizeInPageStandard.swift
Source/UI/VirtusizeInPageView.swift
Source/UI/VirtusizeView.swift
Source/UI/VirtusizeViewStyle.swift
Virtusize.xcodeproj/project.pbxproj

Feature: Add the loading screens for InPage Standard and InPage Mini

---

CHANGES.md
README.md
ROADMAP.md

Update [README.md](https://github.com/virtusize/integration_ios/blob/2dc4456f65912ea95335b4d8eb33aa67ad45d2cb/README.md) with the InPage integration guide

Feature: Update README with the InPage integration guide

---

Source/Internal/API/APIEndpoints.swift
Source/Internal/API/APIRequest.swift
Source/Internal/Views/VirtusizeProductImageView.swift
Source/Models/VirtusizeProductSize.swift
Source/Models/VirtusizeStoreProduct.swift
Source/UI/VirtusizeView.swift
Source/Virtusize.swift
Tests/APIEndpointsTests.swift
Tests/APIRequestTests.swift
Tests/UserProductFixtures.swift
Tests/VirtusizeProductSizeTests.swift
Tests/VirtusizeTests.swift
Virtusize.xcodeproj/project.pbxproj

API integration to get the user product list from API endpoint `/user-products`

Feature: API integration for endpoint /user-products

---

Source/Internal/API/APIEndpoints.swift
Source/Internal/API/APIRequest.swift
Source/Internal/Views/VirtusizeProductImageView.swift
Source/Models/VirtusizeUserBodyProfile.swift
Source/UI/VirtusizeView.swift
Source/Virtusize.swift
Tests/APIEndpointsTests.swift
Tests/APIRequestTests.swift
Tests/UserBodyProfileFixtures.swift
Tests/VirtusizeTests.swift
Tests/VirtusizeUserBodyProfileTests.swift
Virtusize.xcodeproj/project.pbxproj

Feature: API integration to get user body measurement data

---

Source/Internal/Models/SizeComparisonRecommendedSize.swift
Source/Internal/Models/VirtusizeI18nLocalization.swift
Source/Internal/Models/VirtusizeStoreProduct.swift
Source/Internal/Utils/FindBestFitHelper.swift
Source/Internal/Utils/String+Extensions.swift
Source/Internal/Workers/Deserializer.swift
Source/Localizations/en.lproj/VirtusizeLocalizable.strings
Source/Localizations/ja.lproj/VirtusizeLocalizable.strings
Source/Localizations/ko.lproj/VirtusizeLocalizable.strings
Source/UI/VirtusizeButton.swift
Source/UI/VirtusizeInPageMini.swift
Source/UI/VirtusizeInPageStandard.swift
Source/UI/VirtusizeInPageView.swift
Source/UI/VirtusizeView.swift
Source/UI/VirtusizeViewStyle.swift
Source/Virtusize.swift
Tests/DeserializerTests.swift
Tests/LocalizationTests.swift
Tests/StoreProductFixtures.swift
Tests/VirtusizeStoreProductTests.swift
Tests/i18n_en.json
Tests/i18n_jp.json
Tests/i18n_ko.json
Virtusize.xcodeproj/project.pbxproj

Feature: Implement the logic to get recommendation texts

---

README.md
Source/Internal/API/APIEndpoints.swift
Source/Models/VirtusizeEnvironment.swift
Tests/APIEndpointsTests.swift
Tests/APIEventTests.swift

Update the README to explain how to set the user ID either before or after the app is launched

Feature: Update the README to explain how to set the user ID

---

README.md
Source/Internal/API/APIRequest.swift
Source/Internal/API/APIResponse.swift
Source/Internal/Models/BodyProfileRecommendedSize.swift
Source/Internal/Models/ProductComparisonFitInfo.swift
Source/Internal/Models/SizeComparisonRecommendedSize.swift
Source/Internal/Models/UserSessionInfo.swift
Source/Internal/Models/VirtusizeBrandSizing.swift
Source/Internal/Models/VirtusizeGetSizeParams.swift
Source/Internal/Models/VirtusizeI18nLocalization.swift
Source/Internal/Models/VirtusizeInternalProduct.swift
Source/Internal/Models/VirtusizeStoreProductAdditionalInfo.swift
Source/Internal/Models/VirtusizeUserBodyProfile.swift
Source/Internal/Workers/FindBestFitHelper.swift
Source/Internal/Workers/UserDefaultsHelper.swift
Source/Models/VirtusizeParams.swift
Source/UI/VirtusizeInPageMini.swift
Source/UI/VirtusizeInPageStandard.swift
Source/UI/VirtusizeInPageView.swift
Source/UI/VirtusizeWebViewController.swift
Source/Virtusize.swift
Tests/APIRequestTests.swift
Tests/FindBestFitHelperTests.swift
Tests/VirtusizeStoreProductTests.swift
Virtusize.xcodeproj/project.pbxproj

[README.md](https://github.com/virtusize/integration_ios/tree/c082f9454e73fc4eb2c852a74c49cfb080cc6668)

Feature: Update README and document the code

---

README-JP.md
README.md

[README](https://github.com/virtusize/integration_ios/blob/c40af6aed7fbca445a7be20dd1cfe78d5a5e6033/README-JP.md)

Feature: Add JP README

---

README-JP.md
Source/Internal/API/APIEndpoints.swift
Source/Internal/API/APIRequest.swift
Source/Localizations/ja.lproj/VirtusizeLocalizable.strings
Source/Models/VirtusizeEnvironment.swift
Source/UI/VirtusizeButton.swift
Source/UI/VirtusizeInPageView.swift
Source/UI/VirtusizeView.swift
Source/UI/VirtusizeWebViewController.swift
Source/Virtusize.swift
Tests/APIEndpointsTests.swift
Virtusize.podspec
Virtusize.xcodeproj/project.pbxproj

InPage SDK release 2.1.0 including some fixes:

InPage SDK release: 2.1.0

---

CHANGES.md
README.md
ROADMAP.md
Source/Internal/API/APIEndpoints.swift
Source/Models/VirtusizeEnvironment.swift
Tests/APIEndpointsTests.swift
Virtusize.podspec

Release/1.4.1 Update the PDC URL

---

CHANGES.md
README-JP.md
README.md
Virtusize.podspec

Release: 2.1.3

---

README-JP.md
README.md
SwiftUIExample/SwiftUIExample/ContentView.swift

Update the RADEMEs about the SwiftUI integration
[README.md](https://github.com/virtusize/integration_ios/blob/c07c3c977b94e7d07968d13933140dd537770152/README.md#swiftui-app-integration)
[README-JP.md](https://github.com/virtusize/integration_ios/blob/c07c3c977b94e7d07968d13933140dd537770152/README-JP.md#swiftui-app-integration) (no translation needed until there's an actual need for this SwifUI integration)

Feature: SwiftUI integration guide

---

CHANGES.md
README-JP.md
README.md
Virtusize.podspec
Virtusize/Sources/VirtusizeConfiguration.swift
Virtusize/Tests/APIEventTests.swift
VirtusizeCore.podspec

-  Cleanup: Update VirtusizeAuth POD Version to 1.0.3
-  Docs: Update Readme file to update Requirements: iOS version

Update VirtusizeAuth POD version 1.0.3

---

Example/Example.xcodeproj/project.pbxproj

- Added Required framework in general setting of the project

Fixed Framework not found issue in Example app

---

.githooks/pre-push
Makefile
README.md

Explain the current situation of the code
- Tests are not automatically run on push (similar to Android)

Setup pre-push git hook to run tests (linter runs as part for build for tests)

---

CHANGES.md
VirtusizeCore/Sources/Utils/UIApplication+Extensions.swift

- Click on Privacy Policy does nothing

Fix an issue when external URLs never opened

---

CHANGES.md
Example/Sources/WebViewController.swift
Virtusize/Sources/UI/VirtusizeWebViewController.swift
VirtusizeAuth/Sources/Utils/VirtusizeURLCheck.swift
VirtusizeAuth/Sources/Views/VirtusizeSafariViewController.swift
VirtusizeAuth/Sources/VirtusizeAuthorization.swift
VirtusizeAuth/Sources/VirtusizeWebView.swift
VirtusizeCore/Sources/Utils/UIApplication+Extensions.swift

- Pieces of code for iOS 11 and 13

Old code cleanup
